//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISynergy.Framework.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ISynergy.Framework.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by.
        /// </summary>
        public static string By {
            get {
                return ResourceManager.GetString("By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An instance of a behavior cannot be attached to more than one object at a time..
        /// </summary>
        public static string CannotAttachBehaviorMultipleTimesExceptionMessage {
            get {
                return ResourceManager.GetString("CannotAttachBehaviorMultipleTimesExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find update file..
        /// </summary>
        public static string CannotFindUpdateFile {
            get {
                return ResourceManager.GetString("CannotFindUpdateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot install update..
        /// </summary>
        public static string CannotInstallUpdate {
            get {
                return ResourceManager.GetString("CannotInstallUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapsed.
        /// </summary>
        public static string Collapsed {
            get {
                return ResourceManager.GetString("Collapsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve version information..
        /// </summary>
        public static string CouldNotRetrieveVersionInformation {
            get {
                return ResourceManager.GetString("CouldNotRetrieveVersionInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateBuilder must be called before CreateServiceProvider.
        /// </summary>
        public static string CreateBuilderCallBeforeCreateServiceProvider {
            get {
                return ResourceManager.GetString("CreateBuilderCallBeforeCreateServiceProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day(s).
        /// </summary>
        public static string Day_s {
            get {
                return ResourceManager.GetString("Day_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong.
        ///Contact support..
        /// </summary>
        public static string DefaultException {
            get {
                return ResourceManager.GetString("DefaultException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add an instance of a behavior to a BehaviorCollection more than once..
        /// </summary>
        public static string DuplicateBehaviorInCollectionExceptionMessage {
            get {
                return ResourceManager.GetString("DuplicateBehaviorInCollectionExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter note here....
        /// </summary>
        public static string EnterNote {
            get {
                return ResourceManager.GetString("EnterNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expanded.
        /// </summary>
        public static string Expanded {
            get {
                return ResourceManager.GetString("Expanded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        public static string Fullname {
            get {
                return ResourceManager.GetString("Fullname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good afternoon {0}.
        /// </summary>
        public static string Greeting_Afternoon {
            get {
                return ResourceManager.GetString("Greeting_Afternoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good evening {0}.
        /// </summary>
        public static string Greeting_Evening {
            get {
                return ResourceManager.GetString("Greeting_Evening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good morning {0}.
        /// </summary>
        public static string Greeting_Morning {
            get {
                return ResourceManager.GetString("Greeting_Morning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good night {0}.
        /// </summary>
        public static string Greeting_Night {
            get {
                return ResourceManager.GetString("Greeting_Night", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour(s).
        /// </summary>
        public static string Hour_s {
            get {
                return ResourceManager.GetString("Hour_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string InputFirst {
            get {
                return ResourceManager.GetString("InputFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last change.
        /// </summary>
        public static string InputLast {
            get {
                return ResourceManager.GetString("InputLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssociatedObject is of type {0} but should be of type {1}..
        /// </summary>
        public static string InvalidAssociatedObjectExceptionMessage {
            get {
                return ResourceManager.GetString("InvalidAssociatedObjectExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dutch.
        /// </summary>
        public static string Language_Dutch {
            get {
                return ResourceManager.GetString("Language_Dutch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string Language_English {
            get {
                return ResourceManager.GetString("Language_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        public static string Language_French {
            get {
                return ResourceManager.GetString("Language_French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        public static string Language_German {
            get {
                return ResourceManager.GetString("Language_German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account?.
        /// </summary>
        public static string LoginAccount {
            get {
                return ResourceManager.GetString("LoginAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account?.
        /// </summary>
        public static string LoginNoAccount {
            get {
                return ResourceManager.GetString("LoginNoAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you already have an account, you can use your e-mail address and password to login..
        /// </summary>
        public static string LoginText {
            get {
                return ResourceManager.GetString("LoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have an account?.
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandatory update has failed!.
        /// </summary>
        public static string MandatoryUpdateFailed {
            get {
                return ResourceManager.GetString("MandatoryUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute(s).
        /// </summary>
        public static string Minute_s {
            get {
                return ResourceManager.GetString("Minute_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modules.
        /// </summary>
        public static string Modules {
            get {
                return ResourceManager.GetString("Modules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No internet connection is available..
        /// </summary>
        public static string NoInternetConnectionAvailable {
            get {
                return ResourceManager.GetString("NoInternetConnectionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items available.
        /// </summary>
        public static string NoItems {
            get {
                return ResourceManager.GetString("NoItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only IAction types are supported in an ActionCollection..
        /// </summary>
        public static string NonActionAddedToActionCollectionExceptionMessage {
            get {
                return ResourceManager.GetString("NonActionAddedToActionCollectionExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only IBehavior types are supported in a BehaviorCollection..
        /// </summary>
        public static string NonBehaviorAddedToBehaviorCollectionExceptionMessage {
            get {
                return ResourceManager.GetString("NonBehaviorAddedToBehaviorCollectionExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IServiceProviderFactory returned a null IServiceProvider.
        /// </summary>
        public static string NullIServiceProvider {
            get {
                return ResourceManager.GetString("NullIServiceProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string PasswordForgot {
            get {
                return ResourceManager.GetString("PasswordForgot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retype password.
        /// </summary>
        public static string PasswordRetype {
            get {
                return ResourceManager.GetString("PasswordRetype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin.
        /// </summary>
        public static string Pin {
            get {
                return ResourceManager.GetString("Pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One moment please.
        /// </summary>
        public static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember.
        /// </summary>
        public static string Remember {
            get {
                return ResourceManager.GetString("Remember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resolver returned a null IServiceProviderFactory.
        /// </summary>
        public static string ResolverReturnedNull {
            get {
                return ResourceManager.GetString("ResolverReturnedNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select country.
        /// </summary>
        public static string SelectCountry {
            get {
                return ResourceManager.GetString("SelectCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select time zone.
        /// </summary>
        public static string SelectTimeZone {
            get {
                return ResourceManager.GetString("SelectTimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in here.
        /// </summary>
        public static string SignInHere {
            get {
                return ResourceManager.GetString("SignInHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register here.
        /// </summary>
        public static string SignupHere {
            get {
                return ResourceManager.GetString("SignupHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you don&apos;t have an account, fill out the required fields and register. 
        ///After confirmation of your registration you can use your e-mail address and password to login..
        /// </summary>
        public static string SignupText {
            get {
                return ResourceManager.GetString("SignupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account?.
        /// </summary>
        public static string SignupTitle {
            get {
                return ResourceManager.GetString("SignupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        public static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take photo.
        /// </summary>
        public static string TakePhoto {
            get {
                return ResourceManager.GetString("TakePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this item.
        /// </summary>
        public static string ThisItem {
            get {
                return ResourceManager.GetString("ThisItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timezone.
        /// </summary>
        public static string TimeZone {
            get {
                return ResourceManager.GetString("TimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical error.
        /// </summary>
        public static string TitleCriticalError {
            get {
                return ResourceManager.GetString("TitleCriticalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string TitleError {
            get {
                return ResourceManager.GetString("TitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string TitleInfo {
            get {
                return ResourceManager.GetString("TitleInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string TitleQuestion {
            get {
                return ResourceManager.GetString("TitleQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string TitleWarning {
            get {
                return ResourceManager.GetString("TitleWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string TitleWelcome {
            get {
                return ResourceManager.GetString("TitleWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for updates....
        /// </summary>
        public static string UpdateCheckForUpdates {
            get {
                return ResourceManager.GetString("UpdateCheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading and installing update....
        /// </summary>
        public static string UpdateDownloadAndInstall {
            get {
                return ResourceManager.GetString("UpdateDownloadAndInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to install the update now?.
        /// </summary>
        public static string UpdateExecuteNow {
            get {
                return ResourceManager.GetString("UpdateExecuteNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a new update..
        /// </summary>
        public static string UpdateFoundNewUpdate {
            get {
                return ResourceManager.GetString("UpdateFoundNewUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an update available.
        ///Save your work and restart the application..
        /// </summary>
        public static string UpdateRestart {
            get {
                return ResourceManager.GetString("UpdateRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build can only be called once..
        /// </summary>
        public static string WarningBuildCalled {
            get {
                return ResourceManager.GetString("WarningBuildCalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to restart the application to apply the color changes..
        /// </summary>
        public static string WarningColorChange {
            get {
                return ResourceManager.GetString("WarningColorChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateBuilder must be called before CreateServiceProvider..
        /// </summary>
        public static string WarningCreateBuilderCallBeforeCreateServiceProvider {
            get {
                return ResourceManager.GetString("WarningCreateBuilderCallBeforeCreateServiceProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document size cannot exceed {0}..
        /// </summary>
        public static string WarningDocumentSizeTooBig {
            get {
                return ResourceManager.GetString("WarningDocumentSizeTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to do it now?.
        /// </summary>
        public static string WarningDoYouWantToDoItNow {
            get {
                return ResourceManager.GetString("WarningDoYouWantToDoItNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered e-mail address already exists. Provide a new one and try again..
        /// </summary>
        public static string WarningEmailExists {
            get {
                return ResourceManager.GetString("WarningEmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name is null or empty. Specify a valid file name..
        /// </summary>
        public static string WarningFilenameIsNullOrEmpty {
            get {
                return ResourceManager.GetString("WarningFilenameIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered e-mail address is invalid..
        /// </summary>
        public static string WarningInvalidEmail {
            get {
                return ResourceManager.GetString("WarningInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to restart the application to apply the language changes..
        /// </summary>
        public static string WarningLanguageChange {
            get {
                return ResourceManager.GetString("WarningLanguageChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to enter an (company) name existing of at least 3 characters..
        /// </summary>
        public static string WarningLicenseNameSize {
            get {
                return ResourceManager.GetString("WarningLicenseNameSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mandatory package update failed.
        ///Try again or update the application through the Microsoft Store..
        /// </summary>
        public static string WarningMandatoryUpdateFailed {
            get {
                return ResourceManager.GetString("WarningMandatoryUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered name already exists. Specify a new one and try again..
        /// </summary>
        public static string WarningNameExists {
            get {
                return ResourceManager.GetString("WarningNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no country selected..
        /// </summary>
        public static string WarningNoCountrySelected {
            get {
                return ResourceManager.GetString("WarningNoCountrySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no modules selected. Select at least one..
        /// </summary>
        public static string WarningNoModulesSelected {
            get {
                return ResourceManager.GetString("WarningNoModulesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no timezone selected..
        /// </summary>
        public static string WarningNoTimeZoneSelected {
            get {
                return ResourceManager.GetString("WarningNoTimeZoneSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IServiceProviderFactory returned a null IServiceProvider..
        /// </summary>
        public static string WarningNullIServiceProvider {
            get {
                return ResourceManager.GetString("WarningNullIServiceProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords don&apos;t match!.
        /// </summary>
        public static string WarningPasswordMatch {
            get {
                return ResourceManager.GetString("WarningPasswordMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password should have at least 6 characters and at least 1 lower case letter, 1 upper case letter and 1 number..
        /// </summary>
        public static string WarningPasswordSize {
            get {
                return ResourceManager.GetString("WarningPasswordSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will receive an email that you first need to confirm before you are able to log in..
        /// </summary>
        public static string WarningRegistrationConfirmEmail {
            get {
                return ResourceManager.GetString("WarningRegistrationConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The combination of name and e-mail address already exists. Provide a new name and/or e-mail address and try again..
        /// </summary>
        public static string WarningRegistrationExists {
            get {
                return ResourceManager.GetString("WarningRegistrationExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacing IHostApplicationLifetime is not supported..
        /// </summary>
        public static string WarningReplacingIHostApplicationLifetimeIsNotSupported {
            get {
                return ResourceManager.GetString("WarningReplacingIHostApplicationLifetimeIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will receive an email with a link to reset your password..
        /// </summary>
        public static string WarningResetPassword {
            get {
                return ResourceManager.GetString("WarningResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resolver returned a null IServiceProviderFactory..
        /// </summary>
        public static string WarningResolverReturnedNull {
            get {
                return ResourceManager.GetString("WarningResolverReturnedNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WarningSynchronizationRestart.
        /// </summary>
        public static string WarningSynchronizationRestart {
            get {
                return ResourceManager.GetString("WarningSynchronizationRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username should contain at least 3 characters..
        /// </summary>
        public static string WarningUsernameSize {
            get {
                return ResourceManager.GetString("WarningUsernameSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacing IHostApplicationLifetime is not supported..
        /// </summary>
        public static string WindowsAppSdkHostReplacingIHostApplicationLifetimeIsNotSupported {
            get {
                return ResourceManager.GetString("WindowsAppSdkHostReplacingIHostApplicationLifetimeIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
