namespace ISynergy.Framework.Payment.Mollie.Models.Url
{
    /// <summary>
    /// Class UrlObjectLink.
    /// Implements the <see cref="UrlLink" />
    /// </summary>
    /// <typeparam name="T"></typeparam>
    /// <seealso cref="UrlLink" />
    /// <autogeneratedoc />
    public class UrlObjectLink<T> : UrlLink { }
}
