using System.Collections.Generic;

namespace ISynergy.Framework.Payment.Mollie.Models.Order
{
    /// <summary>
    /// Class OrderLineCancellationRequest.
    /// </summary>
    /// <autogeneratedoc />
    public class OrderLineCancellationRequest
    {
        /// <summary>
        /// Gets or sets the lines.
        /// </summary>
        /// <value>The lines.</value>
        /// <autogeneratedoc />
        public IEnumerable<OrderLineDetails> Lines { get; set; }
    }
}
