namespace ISynergy.Framework.Payment.Mollie.Options
{
    /// <summary>
    /// Class MollieApiOptions.
    /// </summary>
    /// <autogeneratedoc />
    public class MollieApiOptions
    {
        /// <summary>
        /// Gets or sets the API key.
        /// </summary>
        /// <value>The API key.</value>
        /// <autogeneratedoc />
        public string ApiKey { get; set; }
    }
}
