using ISynergy.Framework.Payment.Mollie.Enumerations;

namespace ISynergy.Framework.Payment.Mollie.Models.Profile.Response
{
    /// <summary>
    /// Class Review.
    /// </summary>
    /// <autogeneratedoc />
    public class Review
    {
        /// <summary>
        /// Gets or sets the status.
        /// </summary>
        /// <value>The status.</value>
        /// <autogeneratedoc />
        public ReviewStatus Status { get; set; }
    }
}
