using System.Threading.Tasks;
using ISynergy.Framework.Payment.Mollie.Models.Mandate;
using Mollie.Sample.Models;

namespace Mollie.Sample.Services.Mandate
{
    /// <summary>
    /// Interface IMandateOverviewClient
    /// </summary>
    /// <autogeneratedoc />
    public interface IMandateOverviewClient {
        /// <summary>
        /// Gets the list.
        /// </summary>
        /// <param name="customerId">The customer identifier.</param>
        /// <returns>Task&lt;OverviewModel&lt;MandateResponse&gt;&gt;.</returns>
        /// <autogeneratedoc />
        Task<OverviewModel<MandateResponse>> GetList(string customerId);
        /// <summary>
        /// Gets the list by URL.
        /// </summary>
        /// <param name="url">The URL.</param>
        /// <returns>Task&lt;OverviewModel&lt;MandateResponse&gt;&gt;.</returns>
        /// <autogeneratedoc />
        Task<OverviewModel<MandateResponse>> GetListByUrl(string url);
    }
}
