using System;
using System.Threading;
using System.Threading.Tasks;

namespace ISynergy.Framework.Storage.Abstractions
{
    /// <summary>
    /// Interface IStorageService
    /// </summary>
    /// <autogeneratedoc />
    public interface IStorageService
    {
        /// <summary>
        /// Uploads the file asynchronous.
        /// </summary>
        /// <param name="file">The file.</param>
        /// <param name="contentType">Type of the content.</param>
        /// <param name="filename">The filename.</param>
        /// <param name="folder">The folder.</param>
        /// <param name="cancellationToken">The cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <returns>Task&lt;Uri&gt;.</returns>
        /// <autogeneratedoc />
        Task<Uri> UploadFileAsync(byte[] file, string contentType, string filename, string folder, CancellationToken cancellationToken = default);
        /// <summary>
        /// Downloads the file asynchronous.
        /// </summary>
        /// <param name="filename">The filename.</param>
        /// <param name="folder">The folder.</param>
        /// <param name="cancellationToken">The cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <returns>Task&lt;System.Byte[]&gt;.</returns>
        /// <autogeneratedoc />
        Task<byte[]> DownloadFileAsync(string filename, string folder, CancellationToken cancellationToken = default);
        /// <summary>
        /// Updates the file asynchronous.
        /// </summary>
        /// <param name="file">The file.</param>
        /// <param name="contentType">Type of the content.</param>
        /// <param name="filename">The filename.</param>
        /// <param name="folder">The folder.</param>
        /// <param name="cancellationToken">The cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <returns>Task&lt;Uri&gt;.</returns>
        /// <autogeneratedoc />
        Task<Uri> UpdateFileAsync(byte[] file, string contentType, string filename, string folder, CancellationToken cancellationToken = default);
        /// <summary>
        /// Removes the file asynchronous.
        /// </summary>
        /// <param name="filename">The filename.</param>
        /// <param name="folder">The folder.</param>
        /// <param name="cancellationToken">The cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <returns>Task&lt;System.Boolean&gt;.</returns>
        /// <autogeneratedoc />
        Task<bool> RemoveFileAsync(string filename, string folder, CancellationToken cancellationToken = default);
    }
}
