
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1819:Properties should not return arrays", Justification = "<Pending>", Scope = "member", Target = "~P:ISynergy.Services.BaseSettingsService.Wallpaper")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:ISynergy.Framework.Windows.Views.Authentication.Controls.LoginControl.TextBox_Username_QuerySubmitted(Windows.UI.Xaml.Controls.AutoSuggestBox,Windows.UI.Xaml.Controls.AutoSuggestBoxQuerySubmittedEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:ISynergy.Framework.Windows.Views.Authentication.Controls.LoginControl.TextBox_Username_SuggestionChosen(Windows.UI.Xaml.Controls.AutoSuggestBox,Windows.UI.Xaml.Controls.AutoSuggestBoxSuggestionChosenEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:ISynergy.Framework.Windows.Views.ShellView.NavigationItemInvoked(Windows.UI.Xaml.Controls.NavigationView,Windows.UI.Xaml.Controls.NavigationViewItemInvokedEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:ISynergy.Framework.Windows.Views.ShellView.NavigationViewList_ItemClick(System.Object,Windows.UI.Xaml.Controls.ItemClickEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Redundancy", "RCS1163:Unused parameter.", Justification = "<Pending>", Scope = "member", Target = "~M:ISynergy.Framework.Windows.Services.DialogService.ShowAsync(System.String,System.String,ISynergy.Enumerations.MessageBoxButton,ISynergy.Enumerations.MessageBoxImage)~System.Threading.Tasks.Task{ISynergy.Enumerations.MessageBoxResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Redundancy", "RCS1163:Unused parameter.", Justification = "<Pending>", Scope = "member", Target = "~M:ISynergy.Framework.Windows.Views.ShellView.RootNavigationView_BackRequested(Windows.UI.Xaml.Controls.NavigationView,Windows.UI.Xaml.Controls.NavigationViewBackRequestedEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Redundancy", "RCS1163:Unused parameter.", Justification = "<Pending>", Scope = "member", Target = "~M:ISynergy.Framework.Windows.Views.ShellView.RootNavigationView_Loaded(System.Object,Windows.UI.Xaml.RoutedEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1819:Properties should not return arrays", Justification = "<Pending>", Scope = "member", Target = "~P:ISynergy.Framework.Windows.Behaviors.MultiBindingItemCollection.Value")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Redundancy", "RCS1163:Unused parameter.", Justification = "<Pending>", Scope = "member", Target = "~M:ISynergy.Framework.Windows.Controls.ControlWrapper.#ctor")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Redundancy", "RCS1163:Unused parameter.", Justification = "<Pending>", Scope = "member", Target = "~M:ISynergy.Framework.Windows.Controls.BladeView.#ctor")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Redundancy", "RCS1163:Unused parameter.", Justification = "<Pending>", Scope = "member", Target = "~M:ISynergy.Framework.Windows.Controls.PropertyChangeEventSource`1.OnValueChanged(`0,`0)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Redundancy", "RCS1163:Unused parameter.", Justification = "<Pending>", Scope = "member", Target = "~M:ISynergy.Framework.Windows.Controls.DragDrop.Reorder.ReorderItemsCoordinator.AnimateItem(ISynergy.Framework.Windows.Controls.DragDrop.Reorder.IReorderItem,ISynergy.Framework.Windows.Controls.DragDrop.Reorder.IReorderItem,Windows.Foundation.Point)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Redundancy", "RCS1163:Unused parameter.", Justification = "<Pending>", Scope = "member", Target = "~M:ISynergy.Framework.Windows.Controls.Schedule.CalendarMultiDayViewModel.ArrangeAllDayAppointment(ISynergy.Mathematics.BaseRect)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:ISynergy.Framework.Windows.Controls.Schedule.CalendarMultiDayViewModel.ArrangeAllDayAppointment(ISynergy.Mathematics.BaseRect)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Redundancy", "RCS1213:Remove unused member declaration.", Justification = "<Pending>", Scope = "member", Target = "~M:ISynergy.Framework.Windows.Controls.Schedule.XamlHeaderContentLayer.ApplyStyleToDefaultVisual(Windows.UI.Xaml.Controls.TextBlock,ISynergy.Framework.Windows.Controls.Schedule.CalendarCellModel)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Code Quality", "IDE0051:Remove unused private members", Justification = "<Pending>", Scope = "member", Target = "~M:ISynergy.Framework.Windows.Controls.Schedule.XamlHeaderContentLayer.ApplyStyleToDefaultVisual(Windows.UI.Xaml.Controls.TextBlock,ISynergy.Framework.Windows.Controls.Schedule.CalendarCellModel)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0059:Value assigned to symbol is never used", Justification = "<Pending>", Scope = "member", Target = "~M:ISynergy.Framework.Windows.Controls.DragDrop.DragDrop.StartDrag(System.Object,Windows.UI.Xaml.Input.PointerRoutedEventArgs,ISynergy.Framework.Windows.Controls.DragDrop.DragDropTrigger,System.Object)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0059:Value assigned to symbol is never used", Justification = "<Pending>", Scope = "member", Target = "~M:ISynergy.Framework.Windows.Controls.Core.BaseControl.InvokeAsync(Windows.UI.Core.CoreDispatcherPriority,Windows.UI.Core.DispatchedHandler)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Code Quality", "IDE0051:Remove unused private members", Justification = "<Pending>", Scope = "member", Target = "~M:ISynergy.Framework.Windows.Controls.Schedule.Calendar.GetFirstDayofMonth(System.DateTime,System.Globalization.Calendar)~System.DateTime")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0059:Value assigned to symbol is never used", Justification = "<Pending>", Scope = "member", Target = "~M:ISynergy.Framework.Windows.Controls.Schedule.CalendarModel.GetFirstDateToRenderForDisplayMode(System.DateTime,ISynergy.Framework.Windows.Controls.Schedule.CalendarDisplayMode)~System.DateTime")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0059:Value assigned to symbol is never used", Justification = "<Pending>", Scope = "member", Target = "~M:ISynergy.Framework.Windows.Controls.Schedule.CalendarMultiDayViewModel.ArrangeMultiDayViewCalendarDecorations(ISynergy.Mathematics.BaseRect)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0059:Value assigned to symbol is never used", Justification = "<Pending>", Scope = "member", Target = "~M:ISynergy.Framework.Windows.Helpers.VisualHelpers.GetVisualChildByName``1(Windows.UI.Xaml.FrameworkElement,System.String)~``0")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Redundancy", "RCS1163:Unused parameter.", Justification = "<Pending>", Scope = "member", Target = "~M:ISynergy.Framework.Windows.Services.DialogService.ShowAsync(System.String,System.String,ISynergy.Framework.Core.Enumerations.MessageBoxButton,ISynergy.Framework.Core.Enumerations.MessageBoxImage)~System.Threading.Tasks.Task{ISynergy.Framework.Core.Enumerations.MessageBoxResult}")]

