namespace ISynergy.Framework.Payment.Mollie.Models.Error
{
    /// <summary>
    /// Class MollieErrorMessage.
    /// </summary>
    /// <autogeneratedoc />
    public class MollieErrorMessage
    {
        /// <summary>
        /// Gets or sets the status.
        /// </summary>
        /// <value>The status.</value>
        /// <autogeneratedoc />
        public int Status { get; set; }
        /// <summary>
        /// Gets or sets the title.
        /// </summary>
        /// <value>The title.</value>
        /// <autogeneratedoc />
        public string Title { get; set; }
        /// <summary>
        /// Gets or sets the detail.
        /// </summary>
        /// <value>The detail.</value>
        /// <autogeneratedoc />
        public string Detail { get; set; }

        /// <summary>
        /// Returns a <see cref="System.String" /> that represents this instance.
        /// </summary>
        /// <returns>A <see cref="System.String" /> that represents this instance.</returns>
        /// <autogeneratedoc />
        public override string ToString()
        {
            return $"{Title} - {Detail}";
        }
    }
}
