using ISynergy.Framework.Payment.Mollie.Models.Url;

namespace Mollie.Sample.Models
{
    /// <summary>
    /// Class OverviewNavigationLinksModel.
    /// </summary>
    /// <autogeneratedoc />
    public class OverviewNavigationLinksModel {
        /// <summary>
        /// Gets or sets the previous.
        /// </summary>
        /// <value>The previous.</value>
        /// <autogeneratedoc />
        public UrlLink Previous { get; set; }
        /// <summary>
        /// Gets or sets the next.
        /// </summary>
        /// <value>The next.</value>
        /// <autogeneratedoc />
        public UrlLink Next { get; set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="OverviewNavigationLinksModel"/> class.
        /// </summary>
        /// <param name="previous">The previous.</param>
        /// <param name="next">The next.</param>
        /// <autogeneratedoc />
        public OverviewNavigationLinksModel(UrlLink previous, UrlLink next) {
            Previous = previous;
            Next = next;
        }
    }
}
