namespace ISynergy.Framework.Payment.ContractResolvers
{
    /// <summary>
    /// Class SnakeCasePropertyNamesContractResolver.
    /// Implements the <see cref="DeliminatorSeparatedPropertyNamesContractResolver" />
    /// </summary>
    /// <seealso cref="DeliminatorSeparatedPropertyNamesContractResolver" />
    /// <autogeneratedoc />
    public class SnakeCasePropertyNamesContractResolver : DeliminatorSeparatedPropertyNamesContractResolver
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SnakeCasePropertyNamesContractResolver"/> class.
        /// </summary>
        /// <autogeneratedoc />
        public SnakeCasePropertyNamesContractResolver() : base('_')
        {
        }
    }
}
