using System.ComponentModel.DataAnnotations;

namespace Mollie.Sample.Models {
    /// <summary>
    /// Class CreateCustomerModel.
    /// </summary>
    /// <autogeneratedoc />
    public class CreateCustomerModel {
        /// <summary>
        /// Gets or sets the name.
        /// </summary>
        /// <value>The name.</value>
        /// <autogeneratedoc />
        [Required]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the email.
        /// </summary>
        /// <value>The email.</value>
        /// <autogeneratedoc />
        [EmailAddress]
        public string Email { get; set; }
    }
}
