namespace ISynergy.Framework.Payment.Mollie.Models.Payment
{
    /// <summary>
    /// Class Locale.
    /// </summary>
    /// <autogeneratedoc />
    public static class Locale
    {
        /// <summary>
        /// The de de
        /// </summary>
        /// <autogeneratedoc />
        public static string de_DE = "de_DE";
        /// <summary>
        /// The en us
        /// </summary>
        /// <autogeneratedoc />
        public static string en_US = "en_US";
        /// <summary>
        /// The es es
        /// </summary>
        /// <autogeneratedoc />
        public static string es_ES = "es_ES";
        /// <summary>
        /// The fr fr
        /// </summary>
        /// <autogeneratedoc />
        public static string fr_FR = "fr_FR";
        /// <summary>
        /// The nl be
        /// </summary>
        /// <autogeneratedoc />
        public static string nl_BE = "nl_BE";
        /// <summary>
        /// The fr be
        /// </summary>
        /// <autogeneratedoc />
        public static string fr_BE = "fr_BE";
        /// <summary>
        /// The nl nl
        /// </summary>
        /// <autogeneratedoc />
        public static string nl_NL = "nl_BE";
    }
}
