using System.Collections.Generic;
using System.Text;
using ISynergy.Framework.CQRS.SourceGenerator.Parsers;

namespace ISynergy.Framework.CQRS.SourceGenerator.Emitters;

internal static class HandlerRegistrationEmitter
{
    /// <summary>
    /// Emits a static partial class with an <c>AddCQRSHandlers</c> extension method
    /// that registers all discovered handlers into <c>IServiceCollection</c>.
    /// </summary>
    /// <param name="handlers">All discovered handlers across the compilation.</param>
    /// <param name="rootNamespace">The assembly's root namespace (used as the generated class namespace).</param>
    /// <returns>C# source text ready to add to the compilation.</returns>
    public static string Emit(IReadOnlyList<HandlerInfo> handlers, string rootNamespace)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine($"namespace {rootNamespace};");
        sb.AppendLine();
        sb.AppendLine("[global::System.CodeDom.Compiler.GeneratedCode(\"ISynergy.Framework.CQRS.SourceGenerator\", \"1.0.0\")]");
        sb.AppendLine("public static partial class CqrsHandlerRegistrations");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Registers all CQRS command and query handlers discovered at compile time.");
        sb.AppendLine("    /// AOT-safe: no reflection or assembly scanning.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddCQRSHandlers(");
        sb.AppendLine("        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        sb.AppendLine("    {");

        foreach (var h in handlers)
        {
            // Use QualifyTypeName to add global:: only to namespace-qualified names.
            var serviceType = QualifyTypeName(h.ServiceInterfaceName);
            var handlerType = QualifyTypeName(h.HandlerTypeName);
            sb.AppendLine($"        services.AddScoped<{serviceType}, {handlerType}>();");
        }

        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Adds <c>global::</c> prefix to a fully-qualified type name if it is namespace-qualified
    /// (i.e., contains a dot). Built-in keyword types like <c>string</c>, <c>int</c> are returned as-is.
    /// Also recursively qualifies type arguments within generic types.
    /// </summary>
    private static string QualifyTypeName(string typeName)
    {
        // Handle generic types: qualify the outer type and each type argument
        var angleOpen = typeName.IndexOf('<');
        if (angleOpen >= 0)
        {
            var outer = typeName.Substring(0, angleOpen);
            var inner = typeName.Substring(angleOpen + 1, typeName.Length - angleOpen - 2);
            var qualifiedOuter = QualifySingleType(outer);
            var qualifiedInner = QualifyTypeArgList(inner);
            return $"{qualifiedOuter}<{qualifiedInner}>";
        }

        return QualifySingleType(typeName);
    }

    private static string QualifyTypeArgList(string args)
    {
        // Split by comma at the top level (not inside nested generics)
        var result = new StringBuilder();
        var depth = 0;
        var start = 0;
        var first = true;

        for (var i = 0; i < args.Length; i++)
        {
            if (args[i] == '<') depth++;
            else if (args[i] == '>') depth--;
            else if (args[i] == ',' && depth == 0)
            {
                if (!first) result.Append(", ");
                result.Append(QualifyTypeName(args.Substring(start, i - start).Trim()));
                start = i + 1;
                first = false;
            }
        }

        if (!first) result.Append(", ");
        result.Append(QualifyTypeName(args.Substring(start).Trim()));

        return result.ToString();
    }

    private static string QualifySingleType(string name)
    {
        // Only add global:: if this looks like a namespace-qualified name (contains a dot)
        // Built-in types like string, int, bool, etc. do NOT contain dots.
        return name.IndexOf('.') >= 0 ? $"global::{name}" : name;
    }
}
