using Xunit;

namespace ISynergy.Framework.Storage.Tests
{
    /// <summary>
    /// Class UnitTest.
    /// </summary>
    /// <autogeneratedoc />
    public class UnitTest
    {
        /// <summary>
        /// Defines the test method Test.
        /// </summary>
        /// <autogeneratedoc />
        [Fact]
        public void Test()
        {
            Assert.True(true);
        }
    }
}
