namespace ISynergy.Framework.Payment.Mollie.Models
{
    /// <summary>
    /// Class Currency.
    /// </summary>
    /// <autogeneratedoc />
    public static class Currency
    {
        /// <summary>
        /// The aud
        /// </summary>
        /// <autogeneratedoc />
        public static string AUD = nameof(AUD);
        /// <summary>
        /// The BGN
        /// </summary>
        /// <autogeneratedoc />
        public static string BGN = nameof(BGN);
        /// <summary>
        /// The cad
        /// </summary>
        /// <autogeneratedoc />
        public static string CAD = nameof(CAD);
        /// <summary>
        /// The HRK
        /// </summary>
        /// <autogeneratedoc />
        public static string HRK = nameof(HRK);
        /// <summary>
        /// The CZK
        /// </summary>
        /// <autogeneratedoc />
        public static string CZK = nameof(CZK);
        /// <summary>
        /// The DKK
        /// </summary>
        /// <autogeneratedoc />
        public static string DKK = nameof(DKK);
        /// <summary>
        /// The HKD
        /// </summary>
        /// <autogeneratedoc />
        public static string HKD = nameof(HKD);
        /// <summary>
        /// The huf
        /// </summary>
        /// <autogeneratedoc />
        public static string HUF = nameof(HUF);
        /// <summary>
        /// The isk
        /// </summary>
        /// <autogeneratedoc />
        public static string ISK = nameof(ISK);
        /// <summary>
        /// The ils
        /// </summary>
        /// <autogeneratedoc />
        public static string ILS = nameof(ILS);
        /// <summary>
        /// The jpy
        /// </summary>
        /// <autogeneratedoc />
        public static string JPY = nameof(JPY);
        /// <summary>
        /// The nok
        /// </summary>
        /// <autogeneratedoc />
        public static string NOK = nameof(NOK);
        /// <summary>
        /// The PLN
        /// </summary>
        /// <autogeneratedoc />
        public static string PLN = nameof(PLN);
        /// <summary>
        /// The GBP
        /// </summary>
        /// <autogeneratedoc />
        public static string GBP = nameof(GBP);
        /// <summary>
        /// The ron
        /// </summary>
        /// <autogeneratedoc />
        public static string RON = nameof(RON);
        /// <summary>
        /// The sek
        /// </summary>
        /// <autogeneratedoc />
        public static string SEK = nameof(SEK);
        /// <summary>
        /// The CHF
        /// </summary>
        /// <autogeneratedoc />
        public static string CHF = nameof(CHF);
        /// <summary>
        /// The usd
        /// </summary>
        /// <autogeneratedoc />
        public static string USD = nameof(USD);
        /// <summary>
        /// The eur
        /// </summary>
        /// <autogeneratedoc />
        public static string EUR = nameof(EUR);
    }
}
