namespace ISynergy.Framework.Payment.Mollie
{
    /// <summary>
    /// Class Constants.
    /// </summary>
    /// <autogeneratedoc />
    public static class Constants
    {
        /// <summary>
        /// The user agent header
        /// </summary>
        /// <autogeneratedoc />
        public const string UserAgentHeader = "User-Agent";
        /// <summary>
        /// The WWW URL content type
        /// </summary>
        /// <autogeneratedoc />
        public const string WWWUrlContentType = "application/x-www-form-urlencoded"; // http://tools.ietf.org/html/rfc4627
        /// <summary>
        /// The HTTP client default
        /// </summary>
        /// <autogeneratedoc />
        public const string HttpClientDefault = "Default";
        /// <summary>
        /// The HTTP client proxy
        /// </summary>
        /// <autogeneratedoc />
        public const string HttpClientProxy = "Proxy";
        /// <summary>
        /// The API endpoint
        /// </summary>
        /// <autogeneratedoc />
        public const string ApiEndpoint = "https://api.mollie.com/v2/";
    }
}
