# File: pipelines/build.jobs.yml

jobs:
- job: BuildJob
  displayName: 'Build'
  steps:
    - task: NuGetToolInstaller@1
      displayName: 'Use NuGet 4.9.1'
      inputs:
        versionSpec: 4.9.1

    - task: DotNetCoreCLI@2
      displayName: 'Dotnet restore: I-Synergy.Framework.Core'
      inputs:
        command: restore
        projects: 'src\I-Synergy.Framework.Core\I-Synergy.Framework.Core.csproj'
        feedsToUse: config
        nugetConfigPath: nuget.config

    - task: DotNetCoreCLI@2
      displayName: 'Dotnet build: I-Synergy.Framework.Core'
      inputs:
        command: build
        projects: 'src\I-Synergy.Framework.Core\I-Synergy.Framework.Core.csproj'
        arguments: '-c $(BuildConfiguration) -p:Version=$(build.buildNumber)'
        feedsToUse: config
        nugetConfigPath: nuget.config

    - task: DotNetCoreCLI@2
      displayName: 'Dotnet restore: I-Synergy.Framework.Core.Linq'
      inputs:
        command: restore
        projects: 'src\I-Synergy.Framework.Core.Linq\I-Synergy.Framework.Core.Linq.csproj'
        feedsToUse: config
        nugetConfigPath: nuget.config

    - task: DotNetCoreCLI@2
      displayName: 'Dotnet build: I-Synergy.Framework.Core.Linq'
      inputs:
        command: build
        projects: 'src\I-Synergy.Framework.Core.Linq\I-Synergy.Framework.Core.Linq.csproj'
        arguments: '-c $(BuildConfiguration) -p:Version=$(build.buildNumber)'
        feedsToUse: config
        nugetConfigPath: nuget.config

    - task: DotNetCoreCLI@2
      displayName: 'Dotnet restore: I-Synergy.Framework.AspNetCore'
      inputs:
        command: restore
        projects: 'src\I-Synergy.Framework.AspNetCore\I-Synergy.Framework.AspNetCore.csproj'
        feedsToUse: config
        nugetConfigPath: nuget.config

    - task: DotNetCoreCLI@2
      displayName: 'Dotnet build: I-Synergy.Framework.AspNetCore'
      inputs:
        command: build
        projects: 'src\I-Synergy.Framework.AspNetCore\I-Synergy.Framework.AspNetCore.csproj'
        arguments: '-c $(BuildConfiguration) -p:Version=$(build.buildNumber)'
        feedsToUse: config
        nugetConfigPath: nuget.config

    - task: DotNetCoreCLI@2
      displayName: 'Dotnet restore: I-Synergy.Framework.AspNetCore.Authentication'
      inputs:
        command: restore
        projects: 'src\I-Synergy.Framework.AspNetCore.Authentication\I-Synergy.Framework.AspNetCore.Authentication.csproj'
        feedsToUse: config
        nugetConfigPath: nuget.config

    - task: DotNetCoreCLI@2
      displayName: 'Dotnet build: I-Synergy.Framework.AspNetCore.Authentication'
      inputs:
        command: build
        projects: 'src\I-Synergy.Framework.AspNetCore.Authentication\I-Synergy.Framework.AspNetCore.Authentication.csproj'
        arguments: '-c $(BuildConfiguration) -p:Version=$(build.buildNumber)'
        feedsToUse: config
        nugetConfigPath: nuget.config

    - task: DotNetCoreCLI@2
      displayName: 'Dotnet restore: I-Synergy.Framework.EntityFramework'
      inputs:
        command: restore
        projects: 'src\I-Synergy.Framework.EntityFramework\I-Synergy.Framework.EntityFramework.csproj'
        feedsToUse: config
        nugetConfigPath: nuget.config

    - task: DotNetCoreCLI@2
      displayName: 'Dotnet build: I-Synergy.Framework.EntityFramework'
      inputs:
        command: build
        projects: 'src\I-Synergy.Framework.EntityFramework\I-Synergy.Framework.EntityFramework.csproj'
        arguments: '-c $(BuildConfiguration) -p:Version=$(build.buildNumber)'
        feedsToUse: config
        nugetConfigPath: nuget.config

    - task: DotNetCoreCLI@2
      displayName: 'Dotnet restore: I-Synergy.Framework.Financial'
      inputs:
        command: restore
        projects: 'src\I-Synergy.Framework.Financial\I-Synergy.Framework.Financial.csproj'
        feedsToUse: config
        nugetConfigPath: nuget.config

    - task: DotNetCoreCLI@2
      displayName: 'Dotnet build: I-Synergy.Framework.Financial'
      inputs:
        command: build
        projects: 'src\I-Synergy.Framework.Financial\I-Synergy.Framework.Financial.csproj'
        arguments: '-c $(BuildConfiguration) -p:Version=$(build.buildNumber)'
        feedsToUse: config
        nugetConfigPath: nuget.config

    - task: DotNetCoreCLI@2
      displayName: 'Dotnet restore: I-Synergy.Framework.Models'
      inputs:
        command: restore
        projects: 'src\I-Synergy.Framework.Models\I-Synergy.Framework.Models.csproj'
        feedsToUse: config
        nugetConfigPath: nuget.config

    - task: DotNetCoreCLI@2
      displayName: 'Dotnet build: I-Synergy.Framework.Models'
      inputs:
        command: build
        projects: 'src\I-Synergy.Framework.Models\I-Synergy.Framework.Models.csproj'
        arguments: '-c $(BuildConfiguration) -p:Version=$(build.buildNumber)'
        feedsToUse: config
        nugetConfigPath: nuget.config

    - task: DotNetCoreCLI@2
      displayName: 'Dotnet restore: I-Synergy.Framework.Entities'
      inputs:
        command: restore
        projects: 'src\I-Synergy.Framework.Entities\I-Synergy.Framework.Entities.csproj'
        feedsToUse: config
        nugetConfigPath: nuget.config

    - task: DotNetCoreCLI@2
      displayName: 'Dotnet build: I-Synergy.Framework.Entities'
      inputs:
        command: build
        projects: 'src\I-Synergy.Framework.Entities\I-Synergy.Framework.Entities.csproj'
        arguments: '-c $(BuildConfiguration) -p:Version=$(build.buildNumber)'
        feedsToUse: config
        nugetConfigPath: nuget.config

    - task: DotNetCoreCLI@2
      displayName: 'Dotnet restore: I-Synergy.Framework.Geography'
      inputs:
        command: restore
        projects: 'src\I-Synergy.Framework.Geography\I-Synergy.Framework.Geography.csproj'
        feedsToUse: config
        nugetConfigPath: nuget.config

    - task: DotNetCoreCLI@2
      displayName: 'Dotnet build: I-Synergy.Framework.Geography'
      inputs:
        command: build
        projects: 'src\I-Synergy.Framework.Geography\I-Synergy.Framework.Geography.csproj'
        arguments: '-c $(BuildConfiguration) -p:Version=$(build.buildNumber)'
        feedsToUse: config
        nugetConfigPath: nuget.config

    - task: DotNetCoreCLI@2
      displayName: 'Dotnet restore: I-Synergy.Framework.Mathematics'
      inputs:
        command: restore
        projects: 'src\I-Synergy.Framework.Mathematics\I-Synergy.Framework.Mathematics.csproj'
        feedsToUse: config
        nugetConfigPath: nuget.config

    - task: DotNetCoreCLI@2
      displayName: 'Dotnet build: I-Synergy.Framework.Mathematics'
      inputs:
        command: build
        projects: 'src\I-Synergy.Framework.Mathematics\I-Synergy.Framework.Mathematics.csproj'
        arguments: '-c $(BuildConfiguration) -p:Version=$(build.buildNumber)'
        feedsToUse: config
        nugetConfigPath: nuget.config

    - task: DotNetCoreCLI@2
      displayName: 'Dotnet restore: I-Synergy.Framework.MessageBus'
      inputs:
        command: restore
        projects: 'src\I-Synergy.Framework.MessageBus\I-Synergy.Framework.MessageBus.csproj'
        feedsToUse: config
        nugetConfigPath: nuget.config

    - task: DotNetCoreCLI@2
      displayName: 'Dotnet build: I-Synergy.Framework.MessageBus'
      inputs:
        command: build
        projects: 'src\I-Synergy.Framework.MessageBus\I-Synergy.Framework.MessageBus.csproj'
        arguments: '-c $(BuildConfiguration) -p:Version=$(build.buildNumber)'
        feedsToUse: config
        nugetConfigPath: nuget.config

    - task: DotNetCoreCLI@2
      displayName: 'Dotnet restore: I-Synergy.Framework.MessageBus.Azure'
      inputs:
        command: restore
        projects: 'src\I-Synergy.Framework.MessageBus.Azure\I-Synergy.Framework.MessageBus.Azure.csproj'
        feedsToUse: config
        nugetConfigPath: nuget.config

    - task: DotNetCoreCLI@2
      displayName: 'Dotnet build: I-Synergy.Framework.MessageBus.Azure'
      inputs:
        command: build
        projects: 'src\I-Synergy.Framework.MessageBus.Azure\I-Synergy.Framework.MessageBus.Azure.csproj'
        arguments: '-c $(BuildConfiguration) -p:Version=$(build.buildNumber)'
        feedsToUse: config
        nugetConfigPath: nuget.config

    - task: DotNetCoreCLI@2
      displayName: 'Dotnet restore: I-Synergy.Framework.Mvvm'
      inputs:
        command: restore
        projects: 'src\I-Synergy.Framework.Mvvm\I-Synergy.Framework.Mvvm.csproj'
        feedsToUse: config
        nugetConfigPath: nuget.config

    - task: DotNetCoreCLI@2
      displayName: 'Dotnet build: I-Synergy.Framework.Mvvm'
      inputs:
        command: build
        projects: 'src\I-Synergy.Framework.Mvvm\I-Synergy.Framework.Mvvm.csproj'
        arguments: '-c $(BuildConfiguration) -p:Version=$(build.buildNumber)'
        feedsToUse: config
        nugetConfigPath: nuget.config

    - task: DotNetCoreCLI@2
      displayName: 'Dotnet restore: I-Synergy.Framework.Payment'
      inputs:
        command: restore
        projects: 'src\I-Synergy.Framework.Payment\I-Synergy.Framework.Payment.csproj'
        feedsToUse: config
        nugetConfigPath: nuget.config

    - task: DotNetCoreCLI@2
      displayName: 'Dotnet build: I-Synergy.Framework.Payment'
      inputs:
        command: build
        projects: 'src\I-Synergy.Framework.Payment\I-Synergy.Framework.Payment.csproj'
        arguments: '-c $(BuildConfiguration) -p:Version=$(build.buildNumber)'
        feedsToUse: config
        nugetConfigPath: nuget.config

    - task: DotNetCoreCLI@2
      displayName: 'Dotnet restore: I-Synergy.Framework.Payment.Mollie'
      inputs:
        command: restore
        projects: 'src\I-Synergy.Framework.Payment.Mollie\I-Synergy.Framework.Payment.Mollie.csproj'
        feedsToUse: config
        nugetConfigPath: nuget.config

    - task: DotNetCoreCLI@2
      displayName: 'Dotnet build: I-Synergy.Framework.Payment.Mollie'
      inputs:
        command: build
        projects: 'src\I-Synergy.Framework.Payment.Mollie\I-Synergy.Framework.Payment.Mollie.csproj'
        arguments: '-c $(BuildConfiguration) -p:Version=$(build.buildNumber)'
        feedsToUse: config
        nugetConfigPath: nuget.config

    - task: DotNetCoreCLI@2
      displayName: 'Dotnet restore: I-Synergy.Framework.Storage'
      inputs:
        command: restore
        projects: 'src\I-Synergy.Framework.Storage\I-Synergy.Framework.Storage.csproj'
        feedsToUse: config
        nugetConfigPath: nuget.config

    - task: DotNetCoreCLI@2
      displayName: 'Dotnet build: I-Synergy.Framework.Storage'
      inputs:
        command: build
        projects: 'src\I-Synergy.Framework.Storage\I-Synergy.Framework.Storage.csproj'
        arguments: '-c $(BuildConfiguration) -p:Version=$(build.buildNumber)'
        feedsToUse: config
        nugetConfigPath: nuget.config

    - task: DotNetCoreCLI@2
      displayName: 'Dotnet restore: I-Synergy.Framework.Storage.Azure'
      inputs:
        command: restore
        projects: 'src\I-Synergy.Framework.Storage.Azure\I-Synergy.Framework.Storage.Azure.csproj'
        feedsToUse: config
        nugetConfigPath: nuget.config

    - task: DotNetCoreCLI@2
      displayName: 'Dotnet build: I-Synergy.Framework.Storage.Azure'
      inputs:
        command: build
        projects: 'src\I-Synergy.Framework.Storage.Azure\I-Synergy.Framework.Storage.Azure.csproj'
        arguments: '-c $(BuildConfiguration) -p:Version=$(build.buildNumber)'
        feedsToUse: config
        nugetConfigPath: nuget.config

    - task: MSBuild@1
      displayName: 'Framework Windows - Nuget Restore x86'
      inputs:
        solution: 'src\I-Synergy.Framework.Windows\I-Synergy.Framework.Windows.csproj'
        platform: x86
        configuration: '$(BuildConfiguration)'
        msbuildArguments: '/t:restore'
        clean: true

    - task: MSBuild@1
      displayName: 'Framework Windows - Build x86'
      inputs:
        solution: 'src\I-Synergy.Framework.Windows\I-Synergy.Framework.Windows.csproj'
        platform: x86
        configuration: '$(BuildConfiguration)'
        msbuildArguments: '/p:VersionAssembly=$(build.buildNumber)'
        clean: true

    - task: MSBuild@1
      displayName: 'Framework Windows - Nuget Restore x64'
      inputs:
        solution: 'src\I-Synergy.Framework.Windows\I-Synergy.Framework.Windows.csproj'
        platform: x64
        configuration: '$(BuildConfiguration)'
        msbuildArguments: '/t:restore'
        clean: true

    - task: MSBuild@1
      displayName: 'Framework Windows - Build x64'
      inputs:
        solution: 'src\I-Synergy.Framework.Windows\I-Synergy.Framework.Windows.csproj'
        platform: x64
        configuration: '$(BuildConfiguration)'
        msbuildArguments: '/p:VersionAssembly=$(build.buildNumber)'
        clean: true

    - task: MSBuild@1
      displayName: 'Framework Windows - Nuget Restore ARM'
      inputs:
        solution: 'src\I-Synergy.Framework.Windows\I-Synergy.Framework.Windows.csproj'
        platform: ARM
        configuration: '$(BuildConfiguration)'
        msbuildArguments: '/t:restore'
        clean: true

    - task: MSBuild@1
      displayName: 'Framework Windows - Build ARM'
      inputs:
        solution: 'src\I-Synergy.Framework.Windows\I-Synergy.Framework.Windows.csproj'
        platform: ARM
        configuration: '$(BuildConfiguration)'
        msbuildArguments: '/p:VersionAssembly=$(build.buildNumber)'
        clean: true

    - task: MSBuild@1
      displayName: 'Framework Windows - Nuget Restore ARM64'
      inputs:
        solution: 'src\I-Synergy.Framework.Windows\I-Synergy.Framework.Windows.csproj'
        platform: ARM64
        configuration: '$(BuildConfiguration)'
        msbuildArguments: '/t:restore'
        clean: true

    - task: MSBuild@1
      displayName: 'Framework Windows - Build ARM64'
      inputs:
        solution: 'src\I-Synergy.Framework.Windows\I-Synergy.Framework.Windows.csproj'
        platform: ARM64
        configuration: '$(BuildConfiguration)'
        msbuildArguments: '/p:VersionAssembly=$(build.buildNumber)'
        clean: true

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifacts'
      inputs:
        pathtoPublish: '$(System.DefaultWorkingDirectory)\Output'
        artifactName: Output