using System.Runtime.Serialization;

namespace ISynergy.Framework.Payment.Mollie.Enumerations
{
    /// <summary>
    /// Only available for failed payments. Contains a failure reason code.
    /// </summary>
    public enum CreditCardFailureReason
    {
        /// <summary>
        /// The invalid card number
        /// </summary>
        /// <autogeneratedoc />
        [EnumMember(Value = "invalid_card_number")] InvalidCardNumber,
        /// <summary>
        /// The invalid CVV
        /// </summary>
        /// <autogeneratedoc />
        [EnumMember(Value = "invalid_cvv")] InvalidCvv,
        /// <summary>
        /// The invalid card holder name
        /// </summary>
        /// <autogeneratedoc />
        [EnumMember(Value = "invalid_card_holder_name")] InvalidCardHolderName,
        /// <summary>
        /// The card expired
        /// </summary>
        /// <autogeneratedoc />
        [EnumMember(Value = "card_expired")] CardExpired,
        /// <summary>
        /// The invalid card type
        /// </summary>
        /// <autogeneratedoc />
        [EnumMember(Value = "invalid_card_type")] InvalidCardType,
        /// <summary>
        /// The refused by issuer
        /// </summary>
        /// <autogeneratedoc />
        [EnumMember(Value = "refused_by_issuer")] RefusedByIssuer,
        /// <summary>
        /// The insufficient funds
        /// </summary>
        /// <autogeneratedoc />
        [EnumMember(Value = "insufficient_funds")] InsufficientFunds,
        /// <summary>
        /// The inactive card
        /// </summary>
        /// <autogeneratedoc />
        [EnumMember(Value = "inactive_card")] InactiveCard,
        /// <summary>
        /// The unknown reason
        /// </summary>
        /// <autogeneratedoc />
        [EnumMember(Value = "unknown_reason")] UnknownReason,
        /// <summary>
        /// The possible fraud
        /// </summary>
        /// <autogeneratedoc />
        [EnumMember(Value = "possible_fraud")] PossibleFraud
    }
}
