namespace ISynergy.Framework.Payment.Mollie.Enumerations
{
    /// <summary>
    /// Enum CreditCardAudience
    /// </summary>
    /// <autogeneratedoc />
    public enum CreditCardAudience
    {
        /// <summary>
        /// The consumer
        /// </summary>
        /// <autogeneratedoc />
        Consumer,
        /// <summary>
        /// The business
        /// </summary>
        /// <autogeneratedoc />
        Business
    }
}
