namespace ISynergy.Framework.Payment.Mollie.Enumerations
{
    /// <summary>
    /// Enum InvoiceStatus
    /// </summary>
    /// <autogeneratedoc />
    public enum InvoiceStatus
    {
        /// <summary>
        /// The open
        /// </summary>
        /// <autogeneratedoc />
        Open,
        /// <summary>
        /// The paid
        /// </summary>
        /// <autogeneratedoc />
        Paid,
        /// <summary>
        /// The overdue
        /// </summary>
        /// <autogeneratedoc />
        Overdue
    }
}
