using System.Runtime.Serialization;

namespace ISynergy.Framework.Payment.Mollie.Enumerations
{
    /// <summary>
    /// Enum KbcIssuer
    /// </summary>
    /// <autogeneratedoc />
    public enum KbcIssuer
    {
        /// <summary>
        /// The KBC
        /// </summary>
        /// <autogeneratedoc />
        [EnumMember(Value = "kbc")]
        Kbc,
        /// <summary>
        /// The CBC
        /// </summary>
        /// <autogeneratedoc />
        [EnumMember(Value = "cbc")]
        Cbc
    }
}
