using System.Runtime.Serialization;

namespace ISynergy.Framework.Payment.Mollie.Enumerations
{
    /// <summary>
    /// Enum MandateStatus
    /// </summary>
    /// <autogeneratedoc />
    public enum MandateStatus
    {
        /// <summary>
        /// The valid
        /// </summary>
        /// <autogeneratedoc />
        [EnumMember(Value = "valid")]
        Valid,
        /// <summary>
        /// The invalid
        /// </summary>
        /// <autogeneratedoc />
        [EnumMember(Value = "invalid")]
        Invalid,
        /// <summary>
        /// The pending
        /// </summary>
        /// <autogeneratedoc />
        [EnumMember(Value = "pending")]
        Pending
    }
}
