using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace ISynergy.Framework.Payment.Mollie.Enumerations
{
    /// <summary>
    /// Enum Mode
    /// </summary>
    /// <autogeneratedoc />
    [JsonConverter(typeof(StringEnumConverter))]
    public enum Mode
    {
        /// <summary>
        /// The live
        /// </summary>
        /// <autogeneratedoc />
        [EnumMember(Value = "live")]
        Live,
        /// <summary>
        /// The test
        /// </summary>
        /// <autogeneratedoc />
        [EnumMember(Value = "test")]
        Test
    }
}
