using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace ISynergy.Framework.Payment.Mollie.Enumerations
{
    /// <summary>
    /// Enum OrderLineDetailsType
    /// </summary>
    /// <autogeneratedoc />
    [JsonConverter(typeof(StringEnumConverter))]
    public enum OrderLineDetailsType
    {
        /// <summary>
        /// The physical
        /// </summary>
        /// <autogeneratedoc />
        [EnumMember(Value = "physical")] Physical,
        /// <summary>
        /// The discount
        /// </summary>
        /// <autogeneratedoc />
        [EnumMember(Value = "discount")] Discount,
        /// <summary>
        /// The digital
        /// </summary>
        /// <autogeneratedoc />
        [EnumMember(Value = "digital")] Digital,
        /// <summary>
        /// The shipping fee
        /// </summary>
        /// <autogeneratedoc />
        [EnumMember(Value = "shipping_fee")] ShippingFee,
        /// <summary>
        /// The store credit
        /// </summary>
        /// <autogeneratedoc />
        [EnumMember(Value = "store_credit")] StoreCredit,
        /// <summary>
        /// The gift card
        /// </summary>
        /// <autogeneratedoc />
        [EnumMember(Value = "gift_card")] GiftCard,
        /// <summary>
        /// The surcharge
        /// </summary>
        /// <autogeneratedoc />
        [EnumMember(Value = "surcharge")] Surcharge,
    }
}
