namespace ISynergy.Framework.Payment.Mollie.Enumerations
{
    /// <summary>
    /// Enum RefundStatus
    /// </summary>
    /// <autogeneratedoc />
    public enum RefundStatus
    {
        /// <summary>
        /// The pending
        /// </summary>
        /// <autogeneratedoc />
        Pending,
        /// <summary>
        /// The processing
        /// </summary>
        /// <autogeneratedoc />
        Processing,
        /// <summary>
        /// The refunded
        /// </summary>
        /// <autogeneratedoc />
        Refunded,
        /// <summary>
        /// The queued
        /// </summary>
        /// <autogeneratedoc />
        Queued,
        /// <summary>
        /// The failed
        /// </summary>
        /// <autogeneratedoc />
        Failed
    }
}
