using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace ISynergy.Framework.Payment.Mollie.Enumerations
{
    /// <summary>
    /// Enum Resource
    /// </summary>
    /// <autogeneratedoc />
    [JsonConverter(typeof(StringEnumConverter))]
    public enum Resource
    {
        /// <summary>
        /// The orders
        /// </summary>
        /// <autogeneratedoc />
        [EnumMember(Value = "orders")] Orders,
        /// <summary>
        /// The payments
        /// </summary>
        /// <autogeneratedoc />
        [EnumMember(Value = "payments")] Payments
    }
}
