using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace ISynergy.Framework.Payment.Mollie.Enumerations
{
    /// <summary>
    /// Enum SequenceType
    /// </summary>
    /// <autogeneratedoc />
    [JsonConverter(typeof(StringEnumConverter))]
    public enum SequenceType
    {
        /// <summary>
        /// The one off
        /// </summary>
        /// <autogeneratedoc />
        [EnumMember(Value = "oneoff")] OneOff,
        /// <summary>
        /// The first
        /// </summary>
        /// <autogeneratedoc />
        [EnumMember(Value = "first")] First,
        /// <summary>
        /// The recurring
        /// </summary>
        /// <autogeneratedoc />
        [EnumMember(Value = "recurring")] Recurring
    }
}
