namespace ISynergy.Framework.Payment.Mollie.Enumerations
{
    /// <summary>
    /// Enum SettlementStatus
    /// </summary>
    /// <autogeneratedoc />
    public enum SettlementStatus
    {
        /// <summary>
        /// The open
        /// </summary>
        /// <autogeneratedoc />
        Open,
        /// <summary>
        /// The pending
        /// </summary>
        /// <autogeneratedoc />
        Pending,
        /// <summary>
        /// The paid out
        /// </summary>
        /// <autogeneratedoc />
        PaidOut,
        /// <summary>
        /// The failed
        /// </summary>
        /// <autogeneratedoc />
        Failed
    }
}
