namespace ISynergy.Framework.Payment.Mollie.Enumerations
{
    /// <summary>
    /// Enum SubscriptionStatus
    /// </summary>
    /// <autogeneratedoc />
    public enum SubscriptionStatus
    {
        /// <summary>
        /// The pending
        /// </summary>
        /// <autogeneratedoc />
        Pending,
        /// <summary>
        /// The active
        /// </summary>
        /// <autogeneratedoc />
        Active,
        /// <summary>
        /// The canceled
        /// </summary>
        /// <autogeneratedoc />
        Canceled,
        /// <summary>
        /// The suspended
        /// </summary>
        /// <autogeneratedoc />
        Suspended,
        /// <summary>
        /// The completed
        /// </summary>
        /// <autogeneratedoc />
        Completed
    }
}
