# File: pipelines/build.jobs.yml

jobs:
- job: BuildJob
  displayName: 'Build'
  steps:
    - task: NuGetToolInstaller@1
      displayName: 'Use NuGet 4.9.1'
      inputs:
        versionSpec: 4.9.1

    - task: DotNetCoreCLI@2
      displayName: 'Dotnet restore: $(ProjectDescription)'
      inputs:
        command: restore
        projects: 'src\$(ProjectName)\$(ProjectName).csproj'
        feedsToUse: config
        nugetConfigPath: nuget.config

    - task: DotNetCoreCLI@2
      displayName: 'Dotnet build: $(ProjectDescription)'
      inputs:
        command: build
        projects: 'src\$(ProjectName)\$(ProjectName).csproj'
        arguments: '-c $(BuildConfiguration) -p:Version=$(build.buildNumber)'
        feedsToUse: config
        nugetConfigPath: nuget.config

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifacts: $(ProjectDescription)'
      inputs:
        pathtoPublish: '$(System.DefaultWorkingDirectory)\Output'
        artifactName: Output