# File: pipelines/test.jobs.yml

jobs:
- job: TestsJob
  displayName: 'Run Tests'
  steps:
    - task: DotNetCoreCLI@2
      displayName: 'Run Test: $(ProjectDescription)'
      inputs:
        command: test
        projects: 'tests\$(ProjectName).Tests\$(ProjectName).Tests.csproj'
        arguments: '-c $(BuildConfiguration)'