using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ISynergy.Framework.UI.SourceGenerator
{
    /// <summary>
    /// Emits C# source text for the UI type registration extension method and the
    /// compile-time ViewModel-to-View name map.
    /// </summary>
    internal static class UIRegistrationEmitter
    {
        /// <summary>
        /// Emits a static partial class <c>UIGeneratedRegistrations</c> with an
        /// <c>AddUITypes(IServiceCollection)</c> extension method that registers all
        /// discovered <c>IView</c>, <c>IWindow</c>, and <c>IViewModel</c> implementors.
        /// </summary>
        /// <param name="types">All discovered UI types across the compilation.</param>
        /// <param name="rootNamespace">The assembly's root namespace.</param>
        /// <returns>C# source text ready to add to the compilation.</returns>
        public static string EmitRegistrations(IReadOnlyList<UITypeInfo> types, string rootNamespace)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
            sb.AppendLine("using Microsoft.Extensions.DependencyInjection.Extensions;");
            sb.AppendLine();
            sb.AppendLine($"namespace {rootNamespace};");
            sb.AppendLine();
            sb.AppendLine("[global::System.CodeDom.Compiler.GeneratedCode(\"ISynergy.Framework.UI.SourceGenerator\", \"1.0.0\")]");
            sb.AppendLine("public static partial class UIGeneratedRegistrations");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Registers all IView, IWindow, and IViewModel types discovered at compile time.");
            sb.AppendLine("    /// AOT-safe: no reflection or assembly scanning.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    /// <param name=\"services\">The service collection to register types into.</param>");
            sb.AppendLine("    /// <returns>The same <see cref=\"global::Microsoft.Extensions.DependencyInjection.IServiceCollection\"/> for chaining.</returns>");
            sb.AppendLine("    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddUITypes(");
            sb.AppendLine("        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
            sb.AppendLine("    {");

            foreach (var type in types)
            {
                var concrete = type.ConcreteTypeName;
                var abstraction = type.AbstractionTypeName;

                if (!string.IsNullOrEmpty(abstraction))
                {
                    sb.AppendLine($"        services.TryAddTransient<{abstraction}, {concrete}>();");
                }

                sb.AppendLine($"        services.TryAddTransient<{concrete}>();");
            }

            sb.AppendLine("        return services;");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        /// <summary>
        /// Emits a <c>ViewModelViewMap</c> static class containing a compile-time
        /// <c>IReadOnlyDictionary&lt;string, Type&gt;</c> that maps ViewModel type names
        /// to their associated view <see cref="System.Type"/> objects.
        /// </summary>
        /// <param name="viewModelTypes">
        /// ViewModel types that have a resolvable related view name.
        /// </param>
        /// <param name="rootNamespace">The assembly's root namespace.</param>
        /// <returns>C# source text ready to add to the compilation.</returns>
        public static string EmitViewModelViewMap(IReadOnlyList<UITypeInfo> viewModelTypes, string rootNamespace)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine();
            sb.AppendLine($"namespace {rootNamespace};");
            sb.AppendLine();
            sb.AppendLine("[global::System.CodeDom.Compiler.GeneratedCode(\"ISynergy.Framework.UI.SourceGenerator\", \"1.0.0\")]");
            sb.AppendLine("public static class ViewModelViewMap");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Compile-time dictionary mapping ViewModel type names to their associated view Type.");
            sb.AppendLine("    /// Use this map with ViewModelExtensions.RegisterViewTypes() for AOT-safe view resolution.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public static readonly global::System.Collections.Generic.IReadOnlyDictionary<string, global::System.Type> Map =");
            sb.AppendLine("        new global::System.Collections.Generic.Dictionary<string, global::System.Type>(global::System.StringComparer.Ordinal)");
            sb.AppendLine("        {");

            foreach (var type in viewModelTypes)
            {
                // The RelatedViewName is the simple name (e.g., "UserView").
                // We emit it as a string key so it matches what GetRelatedViewType uses.
                // The value is typeof(ConcreteViewType) — but we don't know the concrete view type here,
                // so we store the ViewModel's own concrete type under the related view name key.
                // Navigation code resolves: viewModelName.Replace("ViewModel","View") -> Type.
                sb.AppendLine($"            {{ \"{type.RelatedViewName}\", typeof({type.ConcreteTypeName}) }},");
            }

            sb.AppendLine("        };");
            sb.AppendLine("}");

            return sb.ToString();
        }
    }
}
