namespace ISynergy.Framework.Payment.Mollie.Abstractions.Models
{
    /// <summary>
    /// Interface IResponseObject
    /// </summary>
    /// <autogeneratedoc />
    public interface IResponseObject
    {
    }
}
