using Microsoft.AspNetCore.Mvc;

namespace Mollie.Sample.Controllers {
    /// <summary>
    /// Class HomeController.
    /// Implements the <see cref="Microsoft.AspNetCore.Mvc.Controller" />
    /// </summary>
    /// <seealso cref="Microsoft.AspNetCore.Mvc.Controller" />
    /// <autogeneratedoc />
    public class HomeController : Controller {
        /// <summary>
        /// Indexes this instance.
        /// </summary>
        /// <returns>IActionResult.</returns>
        /// <autogeneratedoc />
        public IActionResult Index() {
            return View();
        }
    }
}
