using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Mollie.Sample.Services.PaymentMethod;

namespace Mollie.Sample.Controllers
{
    /// <summary>
    /// Class PaymentMethodController.
    /// Implements the <see cref="Microsoft.AspNetCore.Mvc.Controller" />
    /// </summary>
    /// <seealso cref="Microsoft.AspNetCore.Mvc.Controller" />
    /// <autogeneratedoc />
    public class PaymentMethodController : Controller {
        /// <summary>
        /// The payment method overview client
        /// </summary>
        /// <autogeneratedoc />
        private readonly IPaymentMethodOverviewClient _paymentMethodOverviewClient;

        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentMethodController"/> class.
        /// </summary>
        /// <param name="paymentMethodOverviewClient">The payment method overview client.</param>
        /// <autogeneratedoc />
        public PaymentMethodController(IPaymentMethodOverviewClient paymentMethodOverviewClient) {
            _paymentMethodOverviewClient = paymentMethodOverviewClient;
        }

        /// <summary>
        /// Indexes this instance.
        /// </summary>
        /// <returns>ViewResult.</returns>
        /// <autogeneratedoc />
        public async Task<ViewResult> Index() {
            var model = await _paymentMethodOverviewClient.GetList();
            return View(model);
        }
    }
}
