using ISynergy.Framework.Synchronization.Core;
using ISynergy.Framework.Synchronization.Core.Batch;
using ISynergy.Framework.Synchronization.Core.Database;
using ISynergy.Framework.Synchronization.Core.Enumerations;
using ISynergy.Framework.Synchronization.Core.Messages;
using ISynergy.Framework.Synchronization.Core.Scopes;
using System;
using System.Runtime.Serialization;

namespace ISynergy.Framework.Synchronization.Client
{
    /// <summary>
    /// HttpMessage send changes response class.
    /// </summary>
    [DataContract(Name = "changesres"), Serializable]
    public class HttpMessageSendChangesResponse : ISerializable
    {
        /// <summary>
        /// Default constructor.
        /// </summary>
        public HttpMessageSendChangesResponse()
        {
        }

        /// <summary>
        /// Default constructor.
        /// </summary>
        /// <param name="context"></param>
        /// <exception cref="ArgumentNullException"></exception>
        public HttpMessageSendChangesResponse(SyncContext context)
            => SyncContext = context ?? throw new ArgumentNullException(nameof(context));

        /// <summary>
        /// special constructor used during deserialization.
        /// </summary>
        protected HttpMessageSendChangesResponse(SerializationInfo info, StreamingContext context)
        {
            SyncContext = (SyncContext)info.GetValue(nameof(SyncContext), typeof(SyncContext)) ?? throw new ArgumentNullException(nameof(SyncContext));
        }

        void ISerializable.GetObjectData(SerializationInfo info, StreamingContext context)
        {
            info.AddValue(nameof(SyncContext), SyncContext);
        }

        /// <summary>
        /// Gets or Sets the Server HttpStep
        /// </summary>
        [DataMember(Name = "ss", IsRequired = true, Order = 1)]

        public HttpStep ServerStep { get; set; }

        /// <summary>
        /// Gets or Sets the SyncContext
        /// </summary>
        [DataMember(Name = "sc", IsRequired = true, Order = 2)]
        public SyncContext SyncContext { get; set; }

        /// <summary>
        /// Gets the current batch index, send from the server 
        /// </summary>
        [DataMember(Name = "bi", IsRequired = true, Order = 3)]
        public int BatchIndex { get; set; }

        /// <summary>
        /// Gets the number of batch to send
        /// </summary>
        [DataMember(Name = "bc", IsRequired = false, Order = 4)]
        public int BatchCount { get; set; }

        /// <summary>
        /// Gets or Sets if this is the last Batch send from the server 
        /// </summary>
        [DataMember(Name = "islb", IsRequired = true, Order = 5)]
        public bool IsLastBatch { get; set; }

        /// <summary>
        /// The remote client timestamp generated by the server database
        /// </summary>
        [DataMember(Name = "rct", IsRequired = true, Order = 6)]
        public long RemoteClientTimestamp { get; set; }

        /// <summary>
        /// Gets the BatchParInfo send from the server 
        /// </summary>
        [DataMember(Name = "changes", IsRequired = true, Order = 7)]
        public ContainerSet Changes { get; set; } // BE CAREFUL: If changes the order, change it too in "ContainerSetBoilerPlate" !

        /// <summary>
        /// Gets the changes stats from the server
        /// </summary>
        [DataMember(Name = "scs", IsRequired = true, Order = 8)]
        public DatabaseChangesSelected ServerChangesSelected { get; set; }

        /// <summary>
        /// Gets the changes stats from the server
        /// </summary>
        [DataMember(Name = "cca", IsRequired = true, Order = 9)]
        public DatabaseChangesApplied ClientChangesApplied { get; set; }

        /// <summary>
        /// Gets or Sets the conflict resolution policy from the server
        /// </summary>

        [DataMember(Name = "policy", IsRequired = true, Order = 10)]
        public ConflictResolutionPolicy ConflictResolutionPolicy { get; set; }


    }

    [DataContract(Name = "morechangesreq"), Serializable]
    public class HttpMessageGetMoreChangesRequest : ISerializable
    {
        public HttpMessageGetMoreChangesRequest() { }

        public HttpMessageGetMoreChangesRequest(SyncContext context, int batchIndexRequested)
        {
            BatchIndexRequested = batchIndexRequested;
            SyncContext = context ?? throw new ArgumentNullException(nameof(context));
        }

        /// <summary>
        /// special constructor used during deserialization.
        /// </summary>
        protected HttpMessageGetMoreChangesRequest(SerializationInfo info, StreamingContext context)
        {
            BatchIndexRequested = (int)info.GetValue(nameof(BatchIndexRequested), typeof(int));
            SyncContext = (SyncContext)info.GetValue(nameof(SyncContext), typeof(SyncContext)) ?? throw new ArgumentNullException(nameof(SyncContext));
        }

        void ISerializable.GetObjectData(SerializationInfo info, StreamingContext context)
        {
            info.AddValue(nameof(BatchIndexRequested), BatchIndexRequested);
            info.AddValue(nameof(SyncContext), SyncContext);
        }


        [DataMember(Name = "sc", IsRequired = true, Order = 1)]
        public SyncContext SyncContext { get; set; }

        [DataMember(Name = "bireq", IsRequired = true, Order = 2)]
        public int BatchIndexRequested { get; set; }
    }

    [DataContract(Name = "changesreq"), Serializable]
    public class HttpMessageSendChangesRequest : ISerializable
    {
        public HttpMessageSendChangesRequest()
        { 
        }

        public HttpMessageSendChangesRequest(SyncContext context, ScopeInfo scope)
        {
            SyncContext = context;
            Scope = scope;
        }

        /// <summary>
        /// special constructor used during deserialization.
        /// </summary>
        protected HttpMessageSendChangesRequest(SerializationInfo info, StreamingContext context)
        {
            SyncContext = (SyncContext)info.GetValue(nameof(SyncContext), typeof(SyncContext));
            Scope = (ScopeInfo)info.GetValue(nameof(Scope), typeof(ScopeInfo));
        }

        void ISerializable.GetObjectData(SerializationInfo info, StreamingContext context)
        {
            info.AddValue(nameof(SyncContext), SyncContext);
            info.AddValue(nameof(Scope), Scope);
        }

        [DataMember(Name = "sc", IsRequired = true, Order = 1)]
        public SyncContext SyncContext { get; set; }

        /// <summary>
        /// Gets or Sets the reference scope for local repository, stored on server
        /// </summary>
        [DataMember(Name = "scope", IsRequired = true, Order = 2)]
        public ScopeInfo Scope { get; set; }

        /// <summary>
        /// Get the current batch index (if InMemory == false)
        /// </summary>
        [DataMember(Name = "bi", IsRequired = true, Order = 3)]
        public int BatchIndex { get; set; }

        /// <summary>
        /// Get the current batch count (if InMemory == false)
        /// </summary>
        [DataMember(Name = "bc", IsRequired = false, Order = 4)]
        public int BatchCount { get; set; }

        /// <summary>
        /// Gets or Sets if this is the last Batch to sent to server 
        /// </summary>
        [DataMember(Name = "islb", IsRequired = true, Order = 5)]
        public bool IsLastBatch { get; set; }

        /// <summary>
        /// Changes to send
        /// </summary>
        [DataMember(Name = "changes", IsRequired = true, Order = 6)]
        public ContainerSet Changes { get; set; }
    }

    [DataContract(Name = "ensureschemares"), Serializable]
    public class HttpMessageEnsureSchemaResponse : ISerializable
    {
        public HttpMessageEnsureSchemaResponse()
        {

        }
        public HttpMessageEnsureSchemaResponse(SyncContext context, ServerScopeInfo serverScopeInfo)
        {
            SyncContext = context ?? throw new ArgumentNullException(nameof(context));
            ServerScopeInfo = serverScopeInfo ?? throw new ArgumentNullException(nameof(serverScopeInfo));
            Schema = serverScopeInfo.Schema;
        }

        /// <summary>
        /// special constructor used during deserialization.
        /// </summary>
        protected HttpMessageEnsureSchemaResponse(SerializationInfo info, StreamingContext context)
        {
            SyncContext = (SyncContext)info.GetValue(nameof(SyncContext), typeof(SyncContext)) ?? throw new ArgumentNullException(nameof(SyncContext));
            ServerScopeInfo = (ServerScopeInfo)info.GetValue(nameof(ServerScopeInfo), typeof(SyncContext)) ?? throw new ArgumentNullException(nameof(ServerScopeInfo));
            Schema = (SyncSet)info.GetValue(nameof(Schema), typeof(SyncSet)) ?? throw new ArgumentNullException(nameof(Schema));
        }

        void ISerializable.GetObjectData(SerializationInfo info, StreamingContext context)
        {
            info.AddValue(nameof(SyncContext), SyncContext);
            info.AddValue(nameof(ServerScopeInfo), ServerScopeInfo);
            info.AddValue(nameof(Schema), Schema);
        }

        [DataMember(Name = "sc", IsRequired = true, Order = 1)]
        public SyncContext SyncContext { get; set; }

        /// <summary>
        /// Gets or Sets the schema because the ServerScopeInfo won't have it since it's marked (on purpose) as IgnoreDataMember (and then not serialized)
        /// </summary>
        [DataMember(Name = "schema", IsRequired = true, Order = 2)]
        public SyncSet Schema { get; set; }

        /// <summary>
        /// Gets or Sets the server scope info, from server
        /// </summary>
        [DataMember(Name = "ssi", IsRequired = true, Order = 3)]
        public ServerScopeInfo ServerScopeInfo { get; set; }
    }


    [DataContract(Name = "ensurescopesres"), Serializable]
    public class HttpMessageEnsureScopesResponse : ISerializable
    {
        public HttpMessageEnsureScopesResponse()
        {

        }
        public HttpMessageEnsureScopesResponse(SyncContext context, ServerScopeInfo serverScopeInfo)
        {
            SyncContext = context ?? throw new ArgumentNullException(nameof(context));
            ServerScopeInfo = serverScopeInfo ?? throw new ArgumentNullException(nameof(serverScopeInfo));
        }

        /// <summary>
        /// special constructor used during deserialization.
        /// </summary>
        protected HttpMessageEnsureScopesResponse(SerializationInfo info, StreamingContext context)
        {
            SyncContext = (SyncContext)info.GetValue(nameof(SyncContext), typeof(SyncContext)) ?? throw new ArgumentNullException(nameof(SyncContext));
            ServerScopeInfo = (ServerScopeInfo)info.GetValue(nameof(ServerScopeInfo), typeof(SyncContext)) ?? throw new ArgumentNullException(nameof(ServerScopeInfo));
        }

        void ISerializable.GetObjectData(SerializationInfo info, StreamingContext context)
        {
            info.AddValue(nameof(SyncContext), SyncContext);
            info.AddValue(nameof(ServerScopeInfo), ServerScopeInfo);
        }

        [DataMember(Name = "sc", IsRequired = true, Order = 1)]
        public SyncContext SyncContext { get; set; }

        /// <summary>
        /// Gets or Sets the schema option (without schema itself, that is not serializable)
        /// </summary>
        [DataMember(Name = "serverscope", IsRequired = true, Order = 2)]
        public ServerScopeInfo ServerScopeInfo { get; set; }
    }


    [DataContract(Name = "ensurereq"), Serializable]
    public class HttpMessageEnsureScopesRequest : ISerializable
    {
        public HttpMessageEnsureScopesRequest() { }

        /// <summary>
        /// Create a new message to web remote server.
        /// Scope info table name is not provided since we do not care about it on the server side
        /// </summary>
        public HttpMessageEnsureScopesRequest(SyncContext context)
        {
            SyncContext = context ?? throw new ArgumentNullException(nameof(context));
        }

        /// <summary>
        /// special constructor used during deserialization.
        /// </summary>
        protected HttpMessageEnsureScopesRequest(SerializationInfo info, StreamingContext context)
        {
            SyncContext = (SyncContext)info.GetValue(nameof(SyncContext), typeof(SyncContext)) ?? throw new ArgumentNullException(nameof(SyncContext));
        }

        void ISerializable.GetObjectData(SerializationInfo info, StreamingContext context)
        {
            info.AddValue(nameof(SyncContext), SyncContext);
        }

        [DataMember(Name = "sc", IsRequired = true, Order = 1)]
        public SyncContext SyncContext { get; set; }
    }


    [DataContract(Name = "summary"), Serializable]
    public class HttpMessageSummaryResponse : ISerializable
    {
        public HttpMessageSummaryResponse()
        {
        }

        public HttpMessageSummaryResponse(SyncContext context)
            => SyncContext = context ?? throw new ArgumentNullException(nameof(context));

        /// <summary>
        /// special constructor used during deserialization.
        /// </summary>
        protected HttpMessageSummaryResponse(SerializationInfo info, StreamingContext context)
        {
            SyncContext = (SyncContext)info.GetValue(nameof(SyncContext), typeof(SyncContext)) ?? throw new ArgumentNullException(nameof(SyncContext));
        }

        void ISerializable.GetObjectData(SerializationInfo info, StreamingContext context)
        {
            info.AddValue(nameof(SyncContext), SyncContext);
        }

        /// <summary>
        /// Gets or Sets the SyncContext
        /// </summary>
        [DataMember(Name = "sc", IsRequired = true, Order = 1)]
        public SyncContext SyncContext { get; set; }

        /// <summary>
        /// Gets or Sets the conflict resolution policy from the server
        /// </summary>

        [DataMember(Name = "bi", IsRequired = false, EmitDefaultValue = false, Order = 2)]
        public BatchInfo BatchInfo { get; set; }

        /// <summary>
        /// The remote client timestamp generated by the server database
        /// </summary>
        [DataMember(Name = "rct", IsRequired = false, EmitDefaultValue = false, Order = 3)]
        public long RemoteClientTimestamp { get; set; }


        [DataMember(Name = "step", IsRequired = true, Order = 4)]
        public HttpStep Step { get; set; }

        /// <summary>
        /// Gets or Sets the container changes when in memory requested by the client
        /// </summary>
        [DataMember(Name = "changes", IsRequired = false, EmitDefaultValue = false, Order = 5)]
        public ContainerSet Changes { get; set; }

        [DataMember(Name = "scs", IsRequired = false, EmitDefaultValue = false, Order = 6)]
        public DatabaseChangesSelected ServerChangesSelected { get; set; }

        [DataMember(Name = "cca", IsRequired = false, EmitDefaultValue = false, Order = 7)]
        public DatabaseChangesApplied ClientChangesApplied { get; set; }

        [DataMember(Name = "crp", IsRequired = false, EmitDefaultValue = false, Order = 8)]
        public ConflictResolutionPolicy ConflictResolutionPolicy { get; set; }

    }
}
