using AutoMapper;
using ISynergy.Framework.Payment.Mollie.Abstractions.Models;
using ISynergy.Framework.Payment.Mollie.Models.List;
using ISynergy.Framework.Payment.Mollie.Models.Url;
using Mollie.Sample.Models;

namespace Mollie.Sample.Services
{
    /// <summary>
    /// Class OverviewClientBase.
    /// </summary>
    /// <typeparam name="T"></typeparam>
    /// <autogeneratedoc />
    public abstract class OverviewClientBase<T> where T : IResponseObject {
        /// <summary>
        /// The mapper
        /// </summary>
        /// <autogeneratedoc />
        private readonly IMapper _mapper;

        /// <summary>
        /// Initializes a new instance of the <see cref="OverviewClientBase{T}"/> class.
        /// </summary>
        /// <param name="mapper">The mapper.</param>
        /// <autogeneratedoc />
        protected OverviewClientBase(IMapper mapper) {
            _mapper = mapper;
        }

        /// <summary>
        /// Maps the specified list.
        /// </summary>
        /// <param name="list">The list.</param>
        /// <returns>OverviewModel&lt;T&gt;.</returns>
        /// <autogeneratedoc />
        protected OverviewModel<T> Map(ListResponse<T> list) {
            return _mapper.Map<OverviewModel<T>>(list);
        }

        /// <summary>
        /// Creates the URL object.
        /// </summary>
        /// <param name="url">The URL.</param>
        /// <returns>UrlObjectLink&lt;ListResponse&lt;T&gt;&gt;.</returns>
        /// <autogeneratedoc />
        protected UrlObjectLink<ListResponse<T>> CreateUrlObject(string url) {
            return new UrlObjectLink<ListResponse<T>> {
                Href = url
            };
        }
    }
}
